version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chooeat
    volumes:
      - ./src/main/resources/static:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
